#!/bin/bash
#
# Univention Server
#  network script: modify resolv.conf
#
# Copyright 2003-2018 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

# Bug #37689: this script is "sourced", not forked! Do not "exit" the process
(
test -z "$interface" && exit 0
[ "$(ucr get interfaces/${interface}/type)" = dhcp ] || exit 0

eval "$(univention-config-registry shell)"

. /usr/share/univention-lib/base.sh
. /usr/share/univention-lib/ucr.sh

if [ -n "$nameserver_option_timeout" ] && ! grep -q timeout /etc/resolv.conf
then
	echo "options timeout:$nameserver_option_timeout" >> /etc/resolv.conf
fi


is_ns () {
	local server="$1"
	[ "$dns_forwarder1" = "$server" ] ||
	[ "$dns_forwarder2" = "$server" ] ||
	[ "$dns_forwarder3" = "$server" ] ||
	[ "$nameserver1" = "$server" ] ||
	[ "$nameserver2" = "$server" ] ||
	[ "$nameserver3" = "$server" ]
}

# On a joined DNS server the DHCP nameserver should be converted to a dns/forwarder.
# But at least one nameserver must be configured via ucr and nameserver/external
# must not be set to true
if	[ -e /var/univention-join/joined ] &&
	is_domain_controller &&
	[ -n "$nameserver1" -o -n "$nameserver2" -o -n "$nameserver3" ] &&
	! is_ucr_true "nameserver/external"
then
	i=1
	new=$(while read key ns
	do
		[ "$key" = nameserver ] || continue
		is_ns "$ns" || continue
		echo "dns/forwarder${i}=${ns}"
		i=$((i+1))
	done </etc/resolv.conf)
	if [ -n "$new" ]
	then
		ucr set $new >/dev/null
		invoke-rc.d bind9 restart
	fi
	# Finally restore file from UCR setting
	ucr commit /etc/resolv.conf
else
	resolv_conf=$(readlink -f "/etc/resolv.conf" 2>/dev/null) ||
		resolv_conf="/etc/resolv.conf"
	new_resolv_conf="${resolv_conf}.ucs.$$"
	# Prefer locally configured NS from UCR before DHCP
	(
		grep -v '^nameserver' "$resolv_conf"
		ucr search --brief --non-empty '^nameserver[123]$' | sed 's/[123]://'
		grep '^nameserver' "$resolv_conf"
	) |
	sed 's/\s\+/ /g' |
	while read line
	do
		[[ "$line" = nameserver* ]] &&
			grep -Fxq "$line" "$new_resolv_conf" ||
			echo "$line"
	done >"$new_resolv_conf"
	chown --reference="$resolv_conf" "$new_resolv_conf"
	chmod --reference="$resolv_conf" "$new_resolv_conf"
	mv "$new_resolv_conf" "$resolv_conf"
fi

exit 0
)
