univention-ad-connector usr/sbin/
univention-adsearch usr/sbin/
univention-connector-list-rejected usr/sbin/
scripts/* usr/share/univention-ad-connector/scripts

conffiles/etc/univention/connector/ad/mapping etc/univention/connector/ad/

19univention-ad-connector.uinst usr/lib/univention-uninstall/
81univention-ad-connector.inst usr/lib/univention-install/

# AD Connector Listener Module
ad-connector.py usr/lib/univention-directory-listener/system
